### ISSUE TITLE
Incompatibility with SpringBoot 2.6

### ISSUE THREAD

**Issue by MieszkoMakuch** [dsyer/spring-boot-legacy#39]
When starting application with `spring-boot-legacy` and `spring-boot-starter-parent` 2.6.X the following error occurs:
```java
java.lang.NoSuchMethodError: 'org.springframework.boot.builder.SpringApplicationBuilder org.springframework.boot.builder.SpringApplicationBuilder.contextClass(java.lang.Class)'
	at org.springframework.boot.legacy.context.web.SpringBootContextLoaderListener.initWebApplicationContext(SpringBootContextLoaderListener.java:105)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
```

`SpringBootContextLoaderListener#initWebApplicationContext` uses `SpringApplicationBuilder#contextClass` method that was deprecated in spring boot 2.6

**Comment by lzwling** [comment]
Would it be possible to release spring boot legacy based on SpringBoot 2.6?
